#!/bin/bash
# extrainst_
# postrm

## MasterRepo.list setup

function finish() {
	f="${1}"

	# No control fd: bail out
	[[ -z "${f}" || -z "${CYDIA}" ]] && return
	cydia=(${CYDIA})

	# Cydia control fd version != 1: bail out
	[[ ${cydia[1]} -eq 1 ]] || return

	echo "finish:${f}" >&${cydia[0]}
}

if [[ `basename $0` == "extrainst_" ]]; then
	case "$1" in
	install )
		echo Updating Sources
		apt update
		finish return
		;;
	upgrade )
		echo Updating Sources
		apt update
		finish return
		;;
	esac
elif [[ `basename $0` == "postrm" ]]; then
	case "$1" in
	remove )
		echo Updating Sources
		apt update
		finish return
		;;
	purge )
		echo Purging
		finish return
		;;
	abort-install )
		echo Aborting install
		finish return
		;;
	upgrade )
		echo Updating Sources
		apt update
		finish return
		;;
	abort-upgrade )
		echo Aborting upgrade
		finish return
		;;
	failed-upgrade )
		echo Failed upgrading
		finish return
		;;
	esac
fi

exit 0
